spring.application.name=demo01
spring.profiles.active=local
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/demo01}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.seed.user-password=${SEED_USER_PASSWORD}
app.seed.admin-password=${SEED_ADMIN_PASSWORD}
app.seed.manager-password=${SEED_MANAGER_PASSWORD}